<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>LuikiBetter</AssemblyName>
    <RootNamespace>LuikiBetter</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <!-- BepInEx -->
    <Reference Include="BepInEx">
      <HintPath>$(GorillaTagPath)\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>

    <!-- Unity -->
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GorillaTagPath)\Gorilla Tag_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(GorillaTagPath)\Gorilla Tag_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.XRModule">
      <HintPath>$(GorillaTagPath)\Gorilla Tag_Data\Managed\UnityEngine.XRModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Plugin.cs" />
    <Compile Include="LuikiBetterMenu.cs" />
    <Compile Include="MenuPage.cs" />

    <Compile Include="Mods\Movement.cs" />
    <Compile Include="Mods\Safety.cs" />
    <Compile Include="Mods\Overpowered.cs" />

    <Compile Include="GUI\LuikiGUI.cs" />
  </ItemGroup>

</Project>
