<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>LuikiBetter</AssemblyName>
    <RootNamespace>LuikiBetter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>REFERENCES\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine">
      <HintPath>REFERENCES\UnityEngine.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>REFERENCES\UnityEngine.CoreModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.XRModule">
      <HintPath>REFERENCES\UnityEngine.XRModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
